### PR TITLE
fix: added filepath walk to traverse through files in sub-dirs

### LINKED ISSUE #3: Add support to traverse into sub-directories
Currently, the code isn't going deep into sub-directories. 

Here's the output of the files scanned.
```
FileName: .git
FileName: .idea
FileName: LICENSE
FileName: README.md
FileName: comments.go
FileName: go.mod
FileName: go.sum
FileName: main.go
FileName: stto
FileName: test
FileName: utils.go
```

### PR DESCRIPTION
**Pull request by Athe1stB**
Closes #3

### CODE REVIEW

**Review by mainak55512 — CHANGES_REQUESTED** [review]
Hi @Athe1stB, ran the changes locally, facing issues to open files from sub-directories, also there are some warnings in getFile() function.
merge_req

**Comment by Athe1stB** [comment]
This issue isn't with the `getFiles()` method. This issue persists from earlier where os isn't able to open the hidden files(files starting with a `.`. 
Will update this as part of this PR.

Also, I do not see any warnings because of `logrus`.   Can you state more about the warning?

**Comment by mainak55512** [comment]
> This issue isn't with the `getFiles()` method. This issue persists from earlier where os isn't able to open the hidden files(files starting with a `.`. Will update this as part of this PR.
> 
> Also, I do not see any warnings because of `logrus`. Can you state more about the warning?

I guess there is some file path related issue, which is leading to panic. In the earlier version if I go to the exact path and then run the command it is working fine, It seems the program is unable to find the exact file location.

And the logrus.Debug method do not expect any placeholder so I believe the %s is causing the warning.
stto_edited

**Comment by mainak55512** [comment]
Hi @Athe1stB, two pull requests have been merged recently, could you please check and adjust your changes accordingly so that merge conflicts can be avoided.

Thanks in advance

**Pull request closed without merging**
