### PR TITLE
Added CodeOfConduct

### PR DESCRIPTION
**Pull request by Abhishek022001**
The Code of Conduct section has been added in Readme.

### CODE REVIEW

**Comment by mainak55512** [comment]
Hi @Abhishek022001, good work! But I would like to have it as a separate file as Code_of_conduct.md and please make it a more elaborate one.

**Review by mainak55512 — CHANGES_REQUESTED** [review]
Please create a separate CODE_OF_CONDUCT.md file for this

**Comment by Abhishek022001** [comment]
Done, please check

**Review by mainak55512 — APPROVED** [review]
Looks good!

**Pull request merged**
